### ISSUE TITLE
Ensure that server live-data-reloads sync new data to any currently-connected players

### ISSUE THREAD

**Issue by falkreon** [DebuggyTeam/tablesaw#7]
### Describe the bug

tablesaw data uses custom syncing, but there is an edge case we haven't tested yet that may need further patching.

### Which side have you encountered the bug on?

Server

### Steps to reproduce

1. Connect to a server with tablesaw
2. Add a datapack to the server while it's running and a player is connected
3. Run the `/reload` command from a client with adequate permission
4. Enter the tablesaw gui and place the ingredient into the input slot
5. Observe the list of available recipes

Expected: The new datapack recipe will be available

Observed: ??? - untested!

**Comment by woodiertexas** [comment]
Was fixed in https://github.com/DebuggyTeam/tablesaw/pull/8.
